import '../styles/globals.css'
export const metadata={
  title:'My Blog',
  description:'Generated by Next.js',
};


export default function RootLayoyt({
  children,
  }: {
  children: React.ReactNode;
}){
    return(
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}